In [3]:
#importing needed libraries
import numpy as np
import pandas as pd

#Load dataset
transactions = pd.read_csv("datasets/nigerian_market_transactions_assignment.csv")
prices = pd.read_csv("datasets/nigerian_market_prices_assignment.csv")

In [13]:
#Transactions dataset showcase
transactions.head()

,transaction_id,market_id,trader_id,trader_name,product,quantity,revenue,payment_method,transaction_date
0,TXN0001,MKT005,TR005,ALHAJI MUSA,Gari,8,86160,Transfer,2024-02-03 13:53
1,TXN0002,MKT004,TR001,SADIYA,Beans,14,492226,POS,2024-01-05 13:46
2,TXN0003,MKT002,TR006,ALHAJI MUSA,Tomatoes,8,283392,Transfer,2024-01-07 16:53
3,TXN0004,MKT003,TR001,Sadiya,Beans,13,248027,Transfer,2024-03-02 10:14
4,TXN0005,MKT005,TR002,Alhaji Musa,Rice,6,46302,Cash,2024-01-27 14:37

In [14]:
#Prices dataset showcase
prices.head()

,market_id,market_name,state,product,price,unit,date,trader_name
0,MKT001,Bodija Market,Oyo,Beans,"₦5,770",Kg,01-02-2024,mama nkechi
1,MKT003,Ogbete Market,Enugu,Yam,"₦2,534",basket,07/02/2024,bello
2,MKT001,Bodija Market,Oyo,Yam,NaN,50kg,22/02/2024,alhaji musa
3,MKT004,Wuse Market,Abuja,Tomatoes,NaN,Paint Rubber,29-01-2024,mama nkechi
4,MKT003,Ogbete Market,Enugu,Gari,-2616,kg,2024/01/31,sadiya

In [ ]:
#Checking for missing values in transactions dataset
transactions.isnull().sum()

In [ ]:
#Checking for missing in Prices datasets
prices.isnull().sum()

In [ ]:
#Checking for missing values from transactions in relative the overall data
(transactions.isnull().sum())/len(transactions)*100

In [ ]:
#Checking for missing values from prices in relative to the overall data
(prices.isnull().sum())/len(prices)*100

In [ ]:
#check for data types
transactions.dtypes

In [ ]:
prices.dtypes

In [15]:
#Derive price from the transactions revenue
transactions["price"] = transactions["revenue"]/transactions["quantity"]

In [ ]:
transactions.head()

In [ ]:
transactions.isnull().sum()

In [ ]:
prices.isnull().sum()

In [ ]:
#Handling missing values from price
#prices["price"] = prices["price"].str.replace('₦', '').str.replace(',', '')

# Step 2: Convert to numeric, turning any invalid values (including NaN) to NaN
prices["price"] = pd.to_numeric(prices["price"])
# Step 3: Now fill the NaN values with the median
prices["price"] = prices["price"].fillna(prices["price"].median())

prices.head()

In [ ]:
prices.isnull().sum()

In [62]:
#Converting the date columns to actual datetime format
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"], errors="coerce")

In [ ]:
transactions.dtypes

In [ ]:
transactions.duplicated().sum()

In [ ]:
transactions.drop_duplicates()

In [79]:
category_summary = transactions.groupby("product").agg({'revenue' : ['mean']})

In [80]:
print(category_summary)

                revenue
                   mean
product
Beans     247028.213542
Gari      258027.760976
Rice      259725.031579
Tomatoes  290855.697917
Yam       271069.009050

In [77]:
category_summary = transactions.groupby("product").agg({
    "price": ['mean'],
    "quantity": "sum",
    "product": "count"
})

In [78]:
print(category_summary)

                 price quantity product
                  mean      sum   count
product
Beans     23294.958333     2031     192
Gari      24993.292683     2108     205
Rice      24930.826316     2035     190
Tomatoes  26531.911458     2050     192
Yam       24324.081448     2495     221

In [82]:
#Merging dataset
merged_data = pd.merge(transactions, prices, on = "product", how = "inner")

In [83]:
merged_data.head()

,transaction_id,market_id_x,trader_id,trader_name_x,product,quantity,revenue,payment_method,transaction_date,price_x,market_id_y,market_name,state,price_y,unit,date,trader_name_y
0,TXN0001,MKT005,TR005,ALHAJI MUSA,Gari,8,86160,Transfer,2024-02-03 13:53:00,10770.0,MKT003,Ogbete Market,Enugu,-2616.0,kg,2024/01/31,sadiya
1,TXN0001,MKT005,TR005,ALHAJI MUSA,Gari,8,86160,Transfer,2024-02-03 13:53:00,10770.0,MKT003,Ogbete Market,Enugu,5367.0,kg,2024/03/19,alhaji musa
2,TXN0001,MKT005,TR005,ALHAJI MUSA,Gari,8,86160,Transfer,2024-02-03 13:53:00,10770.0,MKT004,Wuse Market,Abuja,-1901.0,Basket,2024-03-13,CHINEDU
3,TXN0001,MKT005,TR005,ALHAJI MUSA,Gari,8,86160,Transfer,2024-02-03 13:53:00,10770.0,MKT001,Bodija Market,Oyo,-3639.0,50kg,05-03-2024,chinedu
4,TXN0001,MKT005,TR005,ALHAJI MUSA,Gari,8,86160,Transfer,2024-02-03 13:53:00,10770.0,MKT004,Wuse Market,Abuja,3063.0,basket,2024-03-30,mama nkechi